package com.example.observerdemo;



public enum EventCategory {
	EVENT_CONFERMA_EVENTO,
	EVENT_PRESENTA_ISTANZA,
	EVENT_EXPIRED_AUTO_EXEC,
	EVENT_GET_PROC_EVENT_STATES_MAP,
	EVENT_SMARTFORM_LOADFROMDB,
	EVENT_VISMASCHERA_POPULATE_ATTRS
} 
